### ISSUE TITLE
Api is dead?

### ISSUE THREAD

**Issue by CTK-WARRIOR** [mobibean/cloud-compiler-docs#1]
API is kind of not working, is it dead?

**Comment by bushev** [comment]
Hey @CTK-WARRIOR,

Wow, did you use it? I suppose it was not used by anyone (except our old app) and shut it down a week ago. The app was updated a month ago - https://apps.apple.com/us/app/code-compiler-programming/id1397424959

**Comment by CTK-WARRIOR** [comment]
Well, I came from app and I saw there is some interesting API which I tried to use but it kind of dead now lmao 🤣

**Comment by bushev** [comment]
Got it! Yes, the API was completely rewritten this year. I'll publish some new documents once the work on the app will be done.
